package backend_model.types;

import java.nio.file.Path;
import java.util.List;

/**
 * An assignment generated by a user.
 */
public interface Assignment {
  String getName();
  Path getDirectoryPath();
  List<String> getSrcFileExts();
  List<Path> submissionsAsPaths();
  List<Submission> getSubmissions();
}
