package com.plagus_server.analysis.lingustic.functions;

import com.plagus_server.analysis.lingustic.python.Python3BaseListener;
import com.plagus_server.analysis.lingustic.python.Python3Parser;

import java.util.ArrayList;
import java.util.List;

/**
 * This listener class simply extracts all functions in a Python 3 source file and stores their
 * metadata in a list.
 */
public class FuncListener extends Python3BaseListener {
  private List<FuncData> functions;

  public FuncListener() {
    functions = new ArrayList<>();
  }

  /**
   * Gathers function metadata from ctx.
   *
   * @param ctx Python 3 Function Declaration context, generated by ANTLR
   */
  @Override
  public void enterFuncdef(Python3Parser.FuncdefContext ctx) {
    functions.add(new FuncData(ctx));
  }

  /**
   * Retrieve list of function data objects.
   *
   * @return List of Funcdata
   */
  public List<FuncData> getFunctions() {
    return functions;
  }
}
