package com.plagus_server.analysis.lingustic.functions;

import com.plagus_server.analysis.lingustic.python.Python3Parser;

import java.nio.file.Path;

/**
 * This class represents the metadata of a Python3 function.
 */
public class FuncData {
  private int lineNum;
  private String data; // original function body
  private Python3Parser.FuncdefContext ctx;
  private String renamed; // function body with renamed variables
  private Path path;

  /**
   * One Funcdata instance per function.
   *
   * @param ctx Python3 Function Declaration Context, generated by ANTLR
   */
  public FuncData(Python3Parser.FuncdefContext ctx) {
    this.ctx = ctx;
    this.lineNum = this.ctx.getStart().getLine();
    this.data = this.ctx.getText();
    this.renamed = null;
    this.path = null;
  }

  public int getLineNum() {
    return lineNum;
  }

  public String getData() {
    return data;
  }

  public Python3Parser.FuncdefContext getCtx() {
    return ctx;
  }

  /**
   * Call after running NewVarListener through function definition context.
   *
   * @param renamed function body with renamed variables
   */
  public void setRenamed(String renamed) {
    this.renamed = renamed;
  }

  public String getRenamed() {
    return renamed;
  }

  /**
   * Call after FuncListener is complete with generating FuncData instances.
   *
   * @param path path object for the file that the function resides in
   */
  public void setPath(Path path) {
    this.path = path;
  }

  public Path getPath() {
    return path;
  }

  public static ReportVersion getReportFrom(FuncData data) {
    return new ReportVersion(data.getPath().toString(),
            data.getLineNum(), data.getData(), data.getRenamed());
  }

  public static class ReportVersion {
    private final String path;
    private final int lineNum;
    private final String data; // original function body
    private final String renamedString; // function body with renamed variables

      ReportVersion(String path, int lineNum, String data, String renamedString) {
      this.path = path;
      this.lineNum = lineNum;
      this.data = data;
      this.renamedString = renamedString;
    }
  }
}
